
spring:
  datasource:
    url: jdbc:postgresql://10.0.16.16:5432/aaa?stringtype=unspecified&reWriteBatchedInserts=true
    username: aaa
    password: aaa
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: WorkflowServiceHikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: true
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All tasks
    #指定数据库类型
    database:
      schema-update: true
    #禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: true
    #禁止index跳转到Camunda自带的管理界面，默认true
    webapp:
      index-redirect-enabled: true
    history-level: none
    deployment-resource-pattern: -*.bpmn
    process-engine-name: WorkflowService

