package com.iuin.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;

/**
 * 类签名常量生成注解
 * 在编译时期自动生成类名和方法签名的常量
 * 类似于Lombok的@FieldNameConstants，但专注于类和方法签名
 *
 * @author Generated by Compile-time Code Gen component
 */
@Target({ ElementType.TYPE })
@Retention(RetentionPolicy.SOURCE)
public @interface ClassMetaConstants {

    /**
     * 是否生成枚举类型的常量
     * 默认为false，生成静态常量类
     */
    boolean asEnum() default false;

    /**
     * 生成的常量前缀
     */
    String prefix() default "";

    /**
     * 生成的常量后缀
     */
    String suffix() default "";

    /**
     * 是否只包含公共方法
     * 默认为false，包含所有方法
     */
    boolean onlyPublicMethods() default false;

    /**
     * 是否包含继承的方法
     * 默认为false，只包含当前类定义的方法
     */
    boolean includeInheritedMethods() default false;

    /**
     * 生成的常量类名
     * 默认为"Metas"
     */
    String innerClassName() default "Metas";
}