# 设置Java版本，统一使用Java 17
sourceCompatibility=17
targetCompatibility=17

# 其他构建优化属性

# 开启并行构建和配置缓存
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true


# 自定义属性
projectVersion = '0.0.1-SNAPSHOT'

springAiVersion=1.0.0
springCloudVersion=2025.0.0
springCloudAlibabaVersion=2023.0.3.3
sb_camundaBpmVersion=7.20.0
querydslVersion=5.0.0
