//gradle插件仓库
pluginManagement {

    def secretsFile = file("support-dependencies/configs/secrets/gradle/secrets.properties")
    if (secretsFile.exists()) {
        println("[pluginManagement]加载本地密文")
        def props = new Properties()
        secretsFile.withInputStream { props.load(it) }
        props.each { k, v -> settings.ext[k as String] = v }
    }

    repositories {
        //本地
        mavenLocal()
//        //私服(Nexus)
//        maven {
//            url 'http://10.10.10.11:8080/repository/maven-public/'
//            allowInsecureProtocol = true
//        }
        // 私服(阿里云)
        maven {
            url 'https://packages.aliyun.com/61581a3190f3ca58306f472f/maven/iuin'
            credentials {
                username = (settings.hasProperty('ALIYUN_USERNAME') ? settings.ALIYUN_USERNAME : System.getenv('ALIYUN_USERNAME'))
                password = (settings.hasProperty('ALIYUN_PASSWORD') ? settings.ALIYUN_PASSWORD : System.getenv('ALIYUN_PASSWORD'))
            }
        }
        //国内镜像
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        //gradle官方门户
        gradlePluginPortal()
        //备用
        mavenCentral()
    }
}

//项目依赖仓库
dependencyResolutionManagement {
    //settings 里找不到再去子模块仓库找，允许叠加
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    def secretsFile = file("support-dependencies/configs/secrets/gradle/secrets.properties")
    if (secretsFile.exists()) {
        println("[dependencyResolutionManagement]加载本地密文")
        def props = new Properties()
        secretsFile.withInputStream { props.load(it) }
        props.each { k, v -> settings.ext[k as String] = v }
    }

    repositories {
        //本地
        mavenLocal()
//        //私服(Nexus)
//        maven {
//            url 'http://10.10.10.11:8080/repository/maven-public/'
//            allowInsecureProtocol = true
//        }
        // 私服(阿里云)
        maven {
            url 'https://packages.aliyun.com/61581a3190f3ca58306f472f/maven/iuin'
            credentials {
                username = (settings.hasProperty('ALIYUN_USERNAME') ? settings.ALIYUN_USERNAME : System.getenv('ALIYUN_USERNAME'))
                password = (settings.hasProperty('ALIYUN_PASSWORD') ? settings.ALIYUN_PASSWORD : System.getenv('ALIYUN_PASSWORD'))
            }
        }
        //国内镜像
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        maven { url 'https://jitpack.io' }
        //备用
        mavenCentral()
    }
}

rootProject.name = 'iuin-mall'

// 完全自动包含所有模块
def includeAllModules(baseDir, prefix) {

    baseDir.eachDir { dir ->

        // 跳过特定目录
        def skipList = ['temp', 'gradle', 'data', 'src', 'build', 'out', 'target', 'arthas-output', 'deploy', 'deploys', 'support-dependencies']
        if (dir.name in skipList || dir.name.startsWith('.')) {
            return
        }

        def modulePath = prefix.isEmpty() ? dir.name : "${prefix}:${dir.name}"

        // 打印当前模块路径
        println("[includeAllModules]正在遍历modulePath: ${modulePath}")

        // 检查该目录是否为Gradle模块（包含build.gradle文件）
        if (new File(dir, 'build.gradle').exists()) {
            include "${modulePath}"
        }

        // 递归处理子目录
        includeAllModules(dir, modulePath)
    }
}

// 调用函数自动包含所有component模块
//includeComponentModules(file("${rootDir}/component"), "")
// 调用函数自动包含所有模块
includeAllModules(file("${rootDir}"), "")
