//gradle插件仓库
pluginManagement {

    def secretsFile = file("support-tools/secrets/gradle/secrets.properties")
    if (secretsFile.exists()) {
        println("[pluginManagement]加载本地密文")
        def props = new Properties()
        secretsFile.withInputStream { props.load(it) }
        props.each { k, v -> settings.ext[k as String] = v }
    }

    repositories {
        //本地
        mavenLocal()
//        //私服(Nexus)
//        maven {
//            url 'http://10.10.10.11:8080/repository/maven-public/'
//            allowInsecureProtocol = true
//        }
        // 私服(阿里云)
        maven {
            url 'https://packages.aliyun.com/61581a3190f3ca58306f472f/maven/iuin'
            credentials {
                username = (settings.hasProperty('ALIYUN_USERNAME') ? settings.ALIYUN_USERNAME : System.getenv('ALIYUN_USERNAME'))
                password = (settings.hasProperty('ALIYUN_PASSWORD') ? settings.ALIYUN_PASSWORD : System.getenv('ALIYUN_PASSWORD'))
            }
        }
        //国内镜像
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        //gradle官方门户
        gradlePluginPortal()
        //备用
        mavenCentral()
    }
}

//项目依赖仓库
dependencyResolutionManagement {
    //settings 里找不到再去子模块仓库找，允许叠加
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    def secretsFile = file("support-tools/secrets/gradle/secrets.properties")
    if (secretsFile.exists()) {
        println("[dependencyResolutionManagement]加载本地密文")
        def props = new Properties()
        secretsFile.withInputStream { props.load(it) }
        props.each { k, v -> settings.ext[k as String] = v }
    }

    repositories {
        //本地
        mavenLocal()
//        //私服(Nexus)
//        maven {
//            url 'http://10.10.10.11:8080/repository/maven-public/'
//            allowInsecureProtocol = true
//        }
        // 私服(阿里云)
        maven {
            url 'https://packages.aliyun.com/61581a3190f3ca58306f472f/maven/iuin'
            credentials {
                username = (settings.hasProperty('ALIYUN_USERNAME') ? settings.ALIYUN_USERNAME : System.getenv('ALIYUN_USERNAME'))
                password = (settings.hasProperty('ALIYUN_PASSWORD') ? settings.ALIYUN_PASSWORD : System.getenv('ALIYUN_PASSWORD'))
            }
        }
        //国内镜像
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        maven { url 'https://jitpack.io' }
        //备用
        mavenCentral()
    }
}

rootProject.name = 'iuin-mall'

include 'common-dependencies'

// TODO @Fa 先注释掉先
include 'gateway-service'
//include 'config-service'
include 'sso-server-service'
include 'sso-server-service:sso-server-service-api'
//include 'a-service'
//include 'b-service'
include 'jpa-service'
//include 'workflow-service'
//include 'search-service'
//include 'search-service:search-service-api'
//include 'commodity-service'
//include 'mbp-ui-service'
//include 'shardingsphere-service'
//include 'yapi-service'

include 'common'

include 'component'
//include 'component:arthas-spring-boot-starter'
//include 'component:base-spring-boot-starter'
//include 'component:es-spring-boot-starter'
//include 'component:jpa-spring-boot-starter'
//include 'component:mybatis-plus-spring-boot-starter'
//include 'component:mybatis-plus-mysql-spring-boot-starter'
//include 'component:shardingsphere-spring-boot-starter'
//include 'component:cache-spring-boot-starter'
//include 'component:yapi-spring-boot-starter'
//include 'component:skywalking-spring-boot-starter'
//include 'component:nacos-spring-boot-starter'
//include 'component:ai-spring-boot-starter'

file("${rootDir}/component").eachDirMatch(~/.*-spring-boot-starter/) {
    include "component:${it.name}"
}

include 'component:test'
include 'component:test:feign'
include 'component:test:mysql'
include 'component:test:jpa'
include 'component:test:testcontainers'

include 'component:pluggable-annotation'
include 'component:pluggable-annotation:version-pluggable'
include 'component:pluggable-annotation:take_time_processor'

// 正常包含compile-time-code-gen模块
include 'component:pluggable-annotation:compile-time-code-gen'

include 'agent-service'
include 'mcp-service'
include 'mcp-service:mcp-service-api'
