archivesBaseName = 'ai-spring-boot-starter'
jar.enabled = true
bootJar.enabled = false

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/snapshot' }
    maven {
        name = 'Central Portal Snapshots'
        url = 'https://central.sonatype.com/repository/maven-snapshots/'
    }
}

dependencies {
    implementation project(':common-dependencies')
    implementation project(':common')
    implementation project(':component:base-spring-boot-starter')

    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc'

    implementation 'org.springframework.ai:spring-ai-starter-mcp-client'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    implementation 'org.springframework.ai:spring-ai-starter-model-deepseek'

    developmentOnly 'org.springframework.ai:spring-ai-spring-boot-docker-compose'
}

test {
    useJUnitPlatform()
} 