metadata:
- appName: ''
  dataId: yapi-service.yml
  desc: ''
  group: v1
  type: yaml
- appName: ''
  dataId: sso-server-service.yml
  desc: ''
  group: v1
  type: yaml
- appName: ''
  dataId: common.yml
  desc: ''
  group: v1
  type: yaml
- appName: ''
  dataId: search-service.yml
  desc: ''
  group: v1
  type: yaml
- appName: ''
  dataId: workflow-service.yml
  desc: ''
  group: v1
  type: yaml
- appName: ''
  dataId: commodity-service.yml
  desc: ''
  group: v1
  type: yaml
- appName: ''
  dataId: common-logback.xml
  group: v1
  type: xml
- appName: ''
  dataId: gateway-service.yml
  group: v1
  type: yaml
