server:
  port: @appPort@
logging:
  level:
    root: info
spring:
  application:
    name: @project.name@
#    com.example.demo.repository.UserRepository: debug
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true