
dependencies {
    implementation project(':common-dependencies')
//    implementation project(':common')
    implementation project(':component:base-spring-boot-starter')
    implementation project(':component:skywalking-spring-boot-starter')
    implementation project(':component:nacos-spring-boot-starter')

    implementation project(':component:ai-spring-boot-starter')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.postgresql:postgresql'

    // Lombok for logging and annotations
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

}

test {
    useJUnitPlatform()
} 