pgsql:
  port: 5432
  address: 10.0.0.11
  username: dbadmin
  password: dbadmin
  dbname: iuin

hikari:
  minimum_idle: 2
  maximum_pool_size: 20

redis:
  address: 10.0.1.90
  port: 6379
  password: jfzx_redis

elasticsearch:
  uris: http://23.intranet.company:9200
  username: elastic
  password: kibana


#线上问题排查工具
arthas:
  appName: ${spring.application.name}
  # telnetPort、httpPort为-1 ，则不提供监听端口，为0 ，则提供随机端口（~/logs/arthas/arthas.log (用户目录下面)里可以找到具体端口日志）
  # 如果是防止一个机器上启动多个 arthas端口冲突。可以配置为随机端口，或者配置为 -1，并且通过tunnel server来使用arthas。
  # 通过命令行 telnet 进行连接
  telnetPort: -1
  httpPort: -1
#  telnetPort: 1${server.port}
#  httpPort: 2${server.port}
  # tunnel-server地址
  tunnel-server: ws://arthas:7777/ws

logging:
  level:
    com.iuin: debug
  config: classpath:logback-skywalking.xml
logback:
  path: ${LINGXI_LOGBACK_PATH:../logs}
  maxHistory: ${LINGXI_LOGBACK_MAXHISTORY:7}
  maxFileSize: ${LINGXI_LOGBACK_MAXFILESIZE:100MB}
  totalSizeCap: ${LINGXI_LOGBACK_TOTALSIZECAP:1GB}
  serviceName: ${spring.application.name}
  logstash: '10.0.1.93:5044'

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

feign:
  circuitbreaker:
    enabled: true
  httpclient:
    connection-timeout: 120000
    enabled: true
