server:
  port: 8100
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    min-response-size: 2048   #默认是2048B 大于2048B的就会压缩
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  application:
    name: gateway-service
  cloud:
    # Gateway自己的配置
    gateway:
      httpclient:
        connect-timeout: 120000
      # 允许跨域访问
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true  # 开启通过服务中心的自动根据 serviceId 创建路由的功能
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  redis:
    host: ${redis.address}
    port: ${redis.port}
    password: ${redis.password}
