# 端口
server:
  port: 9001

# sa-token配置
sa-token:
  timeout: 300
  activity-timeout: 60

  # SSO-相关配置
  sso:
    # SSO-Server端 统一认证地址
    auth-url: http://127.0.0.1:9000/sso/auth
    # 使用Http请求校验ticket
    is-http: true
    # SSO-Server端 ticket校验地址
    check-ticket-url: http://127.0.0.1:9000/sso/checkTicket
    # 打开单点注销功能
    is-slo: true
    # 单点注销地址
    slo-url: http://127.0.0.1:9000/sso/signout
    # 接口调用秘钥
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # SSO-Server端 查询userinfo地址
    userinfo-url: http://127.0.0.1:9000/sso/userinfo

spring:
  # 配置 Redis 连接 （此处与SSO-Server端连接不同的Redis）
  redis:
    # Redis数据库索引
    database: 2
    # Redis服务器地址
    host: 10.0.16.16
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: foobared
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    url: jdbc:postgresql://10.0.16.16:5432/aaa?stringtype=unspecified
    username: aaa
    password: aaa
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: SystemServiceHikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

forest:
  # 关闭 forest 请求日志打印
  log-enabled: false
